<?php

$AVAILABLE_LANGUAGES = [
    'en' => ['label' => 'English'],
    'fr' => ['label' => 'Français'],
    'rw' => ['label' => 'Kinyarwanda'],
];

$APP_TRANSLATIONS = [
    'en' => [
        'common.language' => 'Language',
        'common.menu' => 'Menu',
        'common.home' => 'Home',
        'common.dashboard' => 'Dashboard',
        'common.profile' => 'Profile',
        'common.workers' => 'Workers',
        'common.jobs' => 'Jobs',
        'common.post_job' => 'Post Job',
        'common.find_workers' => 'Find Workers',
        'common.my_jobs' => 'My Jobs',
        'common.bookings' => 'Bookings',
        'common.messages' => 'Messages',
        'common.reviews' => 'Reviews',
        'common.help' => 'Help',
        'common.login' => 'Login',
        'common.register' => 'Register',
        'common.loading' => 'Loading...',
        'common.notifications' => 'Notifications',
        'common.back_home' => 'Back to Home',
        'common.next_step' => 'Next Step',
        'common.previous' => 'Previous',
        'common.phone_number' => 'Phone Number',
        'common.password' => 'Password',
        'common.email_address' => 'Email Address',
        'common.first_name' => 'First Name',
        'common.last_name' => 'Last Name',
        'common.sign_in' => 'Sign in',
        'common.sign_up' => 'Sign up',
        'common.create_account' => 'Create Account',
        'common.remember_me' => 'Remember me',
        'common.forgot_password' => 'Forgot Password?',
        'common.terms' => 'Terms of Service',
        'common.privacy' => 'Privacy Policy',
        'nav.profile_settings' => 'Profile Settings',
        'nav.my_reviews' => 'My Reviews',
        'nav.earnings' => 'Earnings',
        'nav.help_support' => 'Help & Support',
        'nav.logout' => 'Logout',
        'nav.confirm_logout' => 'Confirm Logout',
        'nav.confirm_logout_question' => 'Are you sure you want to logout?',
        'nav.confirm_logout_text' => 'You will be redirected to the homepage and will need to login again to access your account.',
        'nav.cancel' => 'Cancel',
        'nav.logout_now' => 'Logout Now',
        'index.nav_services' => 'Services',
        'index.nav_workers' => 'Workers',
        'index.nav_how' => 'How It Works',
        'index.hero_title' => 'Connect with Trusted Household Workers in Kigali',
        'index.hero_subtitle' => 'Find reliable domestic workers for cleaning, cooking, childcare, and more. All workers are verified and reviewed.',
        'index.hero_find_workers' => 'Find Workers',
        'index.hero_post_job' => 'Post a Job',
        'index.hero_get_started' => 'Get Started',
        'index.hero_browse_workers' => 'Browse Workers',
        'index.services_title' => 'Our Services',
        'index.services_subtitle' => 'Professional household services tailored to your needs',
        'index.featured_title' => 'Featured Workers',
        'index.featured_subtitle' => 'Meet some of our top-rated household workers in Kigali',
        'index.view_all_workers' => 'View All Workers',
        'index.no_workers_title' => 'No Workers Available Yet',
        'index.no_workers_text' => 'Be the first to register as a worker and start finding jobs!',
        'index.register_worker' => 'Register as Worker',
        'index.how_title' => 'How It Works',
        'index.how_subtitle' => 'Get connected with household workers in 3 simple steps',
        'index.cta_title' => 'Ready to Find Your Perfect Household Worker?',
        'index.cta_text' => 'Join hundreds of families in Kigali who trust Household Connect for their domestic help needs',
        'index.cta_browse_workers' => 'Browse Workers',
        'index.cta_post_job' => 'Post a Job',
        'index.cta_get_started' => 'Get Started Now',
        'index.footer_explore' => 'Explore',
        'index.footer_services' => 'Services',
        'index.footer_support' => 'Support',
        'index.footer_contact' => 'Get In Touch',
        'index.footer_call' => 'Call',
        'index.footer_email' => 'Email',
        'index.footer_location' => 'Location',
        'index.footer_hours' => 'Hours',
        'index.service_cleaning_title' => 'Professional Cleaning Services',
        'index.service_cleaning_text' => 'Experienced cleaners for thorough home and office cleaning services',
        'login.heading' => 'Login',
        'login.subtitle' => 'Enter your credentials to access your account',
        'login.submit' => 'Login to Your Account',
        'login.no_account' => "Don't have an account?",
        'login.logging_in' => 'Logging in...',
        'login.fill_all' => 'Please fill in all fields',
        'login.success' => 'Welcome back! Login successful. Taking you to your dashboard now.',
        'login.failed' => 'Login failed. Please try again.',
        'login.network' => 'Network error. Please check your connection and try again.',
        'login.forgot_soon' => 'Password reset feature coming soon!',
        'register.heading' => 'Create Account',
        'register.subtitle' => 'Join thousands of families and workers in Kigali',
        'register.step_personal' => 'Personal Info',
        'register.step_account' => 'Account',
        'register.step_role' => 'Role',
        'register.personal_heading' => 'Personal Information',
        'register.personal_subtitle' => 'Tell us about yourself',
        'register.account_heading' => 'Create Your Account',
        'register.account_subtitle' => 'Set up your login credentials',
        'register.role_heading' => 'Choose Your Role',
        'register.role_subtitle' => 'How will you use our platform?',
        'register.password_length' => 'At least 8 characters',
        'register.password_upper' => 'One uppercase letter',
        'register.password_lower' => 'One lowercase letter',
        'register.password_number' => 'One number',
        'register.confirm_password' => 'Confirm Password',
        'register.employer' => 'Employer',
        'register.employer_text' => 'Looking for household workers',
        'register.worker' => 'Worker',
        'register.worker_text' => 'Looking for job opportunities',
        'register.already_account' => 'Already have an account?',
        'register.creating' => 'Creating Account...',
        'register.create_submit' => 'Create Account',
        'register.fill_required' => 'Please fill in all required fields',
        'register.success' => 'Account created successfully! Redirecting to login...',
        'register.failed' => 'Registration failed. Please try again.',
        'register.network' => 'Network error. Please check your connection and try again.',
        'register.invalid_first' => 'Please enter your first name',
        'register.invalid_last' => 'Please enter your last name',
        'register.invalid_email' => 'Please enter a valid email address',
        'register.invalid_phone' => 'Please enter your phone number',
        'register.invalid_password' => 'Password does not meet requirements',
        'register.invalid_confirm' => 'Passwords do not match',
        'register.invalid_role' => 'Please select your role',
        'register.invalid_terms' => 'You must agree to the terms and conditions',
        'auth.method_not_allowed' => 'Method not allowed',
        'auth.validation_failed' => 'Validation failed',
        'auth.invalid_phone' => 'Invalid phone number format',
        'auth.invalid_credentials' => 'Invalid phone number or password',
        'auth.login_success' => 'Login successful',
        'auth.server_error' => 'Server error',
        'auth.invalid_email' => 'Please enter a valid email address',
        'auth.phone_required' => 'Please enter a valid phone number',
        'auth.password_length' => 'Password must be at least 8 characters long',
        'auth.password_upper' => 'Password must contain at least one uppercase letter',
        'auth.password_lower' => 'Password must contain at least one lowercase letter',
        'auth.password_number' => 'Password must contain at least one number',
        'auth.name_length' => 'Name must be at least 2 characters long',
        'auth.name_letters' => 'Name can only contain letters and spaces',
        'auth.invalid_role' => 'Invalid role',
        'auth.email_exists' => 'Email already registered',
        'auth.phone_exists' => 'Phone number already registered',
        'auth.registration_success' => 'Registration successful',
        'auth.registration_failed' => 'Registration failed',
    ],
    'fr' => [
        'common.language' => 'Langue','common.menu' => 'Menu','common.home' => 'Accueil','common.dashboard' => 'Tableau de bord','common.profile' => 'Profil','common.workers' => 'Travailleurs','common.jobs' => 'Offres','common.post_job' => 'Publier une offre','common.find_workers' => 'Trouver des travailleurs','common.my_jobs' => 'Mes offres','common.bookings' => 'Reservations','common.messages' => 'Messages','common.reviews' => 'Avis','common.help' => 'Aide','common.login' => 'Connexion','common.register' => 'Inscription','common.loading' => 'Chargement...','common.notifications' => 'Notifications','common.back_home' => 'Retour a l\'accueil','common.next_step' => 'Etape suivante','common.previous' => 'Precedent','common.phone_number' => 'Numero de telephone','common.password' => 'Mot de passe','common.email_address' => 'Adresse e-mail','common.first_name' => 'Prenom','common.last_name' => 'Nom','common.sign_in' => 'Se connecter','common.sign_up' => 'S\'inscrire','common.create_account' => 'Creer un compte','common.remember_me' => 'Se souvenir de moi','common.forgot_password' => 'Mot de passe oublie ?','common.terms' => 'Conditions d\'utilisation','common.privacy' => 'Politique de confidentialite','nav.profile_settings' => 'Parametres du profil','nav.my_reviews' => 'Mes avis','nav.earnings' => 'Revenus','nav.help_support' => 'Aide et support','nav.logout' => 'Deconnexion','nav.confirm_logout' => 'Confirmer la deconnexion','nav.confirm_logout_question' => 'Voulez-vous vraiment vous deconnecter ?','nav.confirm_logout_text' => 'Vous serez redirige vers la page d\'accueil et devrez vous reconnecter pour acceder a votre compte.','nav.cancel' => 'Annuler','nav.logout_now' => 'Se deconnecter','index.nav_services' => 'Services','index.nav_workers' => 'Travailleurs','index.nav_how' => 'Comment ca marche','index.hero_title' => 'Trouvez des travailleurs domestiques de confiance a Kigali','index.hero_subtitle' => 'Trouvez des aides menageres fiables pour le nettoyage, la cuisine, la garde d\'enfants et plus encore. Tous les profils sont verifies et notes.','index.hero_find_workers' => 'Trouver des travailleurs','index.hero_post_job' => 'Publier une offre','index.hero_get_started' => 'Commencer','index.hero_browse_workers' => 'Voir les travailleurs','index.services_title' => 'Nos services','index.services_subtitle' => 'Des services domestiques professionnels adaptes a vos besoins','index.featured_title' => 'Travailleurs en vedette','index.featured_subtitle' => 'Decouvrez quelques-uns de nos meilleurs travailleurs domestiques a Kigali','index.view_all_workers' => 'Voir tous les travailleurs','index.no_workers_title' => 'Aucun travailleur disponible pour le moment','index.no_workers_text' => 'Soyez la premiere personne a vous inscrire comme travailleur et commencez a trouver des missions !','index.register_worker' => 'S\'inscrire comme travailleur','index.how_title' => 'Comment ca marche','index.how_subtitle' => 'Trouvez un travailleur domestique en 3 etapes simples','index.cta_title' => 'Pret a trouver le travailleur domestique ideal ?','index.cta_text' => 'Rejoignez des centaines de familles a Kigali qui font confiance a Household Connect pour leur aide a domicile','index.cta_browse_workers' => 'Voir les travailleurs','index.cta_post_job' => 'Publier une offre','index.cta_get_started' => 'Commencer maintenant','index.footer_explore' => 'Explorer','index.footer_services' => 'Services','index.footer_support' => 'Support','index.footer_contact' => 'Nous contacter','index.footer_call' => 'Telephone','index.footer_email' => 'E-mail','index.footer_location' => 'Lieu','index.footer_hours' => 'Horaires','login.heading' => 'Connexion','login.subtitle' => 'Entrez vos identifiants pour acceder a votre compte','login.submit' => 'Se connecter a votre compte','login.no_account' => 'Vous n\'avez pas de compte ?','login.logging_in' => 'Connexion...','login.fill_all' => 'Veuillez remplir tous les champs','login.success' => 'Bon retour ! Connexion reussie. Redirection vers votre tableau de bord.','login.failed' => 'Echec de la connexion. Veuillez reessayer.','login.network' => 'Erreur reseau. Verifiez votre connexion et reessayez.','login.forgot_soon' => 'La reinitialisation du mot de passe sera bientot disponible !','register.heading' => 'Creer un compte','register.subtitle' => 'Rejoignez des milliers de familles et travailleurs a Kigali','register.step_personal' => 'Infos perso','register.step_account' => 'Compte','register.step_role' => 'Role','register.personal_heading' => 'Informations personnelles','register.personal_subtitle' => 'Parlez-nous de vous','register.account_heading' => 'Creez votre compte','register.account_subtitle' => 'Configurez vos identifiants de connexion','register.role_heading' => 'Choisissez votre role','register.role_subtitle' => 'Comment utiliserez-vous notre plateforme ?','register.password_length' => 'Au moins 8 caracteres','register.password_upper' => 'Une lettre majuscule','register.password_lower' => 'Une lettre minuscule','register.password_number' => 'Un chiffre','register.confirm_password' => 'Confirmer le mot de passe','register.employer' => 'Employeur','register.employer_text' => 'Je cherche des travailleurs domestiques','register.worker' => 'Travailleur','register.worker_text' => 'Je cherche des opportunites d\'emploi','register.already_account' => 'Vous avez deja un compte ?','register.creating' => 'Creation du compte...','register.create_submit' => 'Creer un compte','register.fill_required' => 'Veuillez remplir tous les champs obligatoires','register.success' => 'Compte cree avec succes ! Redirection vers la connexion...','register.failed' => 'Echec de l\'inscription. Veuillez reessayer.','register.network' => 'Erreur reseau. Verifiez votre connexion et reessayez.','register.invalid_first' => 'Veuillez saisir votre prenom','register.invalid_last' => 'Veuillez saisir votre nom','register.invalid_email' => 'Veuillez saisir une adresse e-mail valide','register.invalid_phone' => 'Veuillez saisir votre numero de telephone','register.invalid_password' => 'Le mot de passe ne respecte pas les exigences','register.invalid_confirm' => 'Les mots de passe ne correspondent pas','register.invalid_role' => 'Veuillez choisir votre role','register.invalid_terms' => 'Vous devez accepter les conditions','auth.method_not_allowed' => 'Methode non autorisee','auth.validation_failed' => 'Echec de validation','auth.invalid_phone' => 'Format du numero de telephone invalide','auth.invalid_credentials' => 'Numero de telephone ou mot de passe invalide','auth.login_success' => 'Connexion reussie','auth.server_error' => 'Erreur du serveur','auth.invalid_email' => 'Veuillez saisir une adresse e-mail valide','auth.phone_required' => 'Veuillez saisir un numero de telephone valide','auth.password_length' => 'Le mot de passe doit contenir au moins 8 caracteres','auth.password_upper' => 'Le mot de passe doit contenir au moins une lettre majuscule','auth.password_lower' => 'Le mot de passe doit contenir au moins une lettre minuscule','auth.password_number' => 'Le mot de passe doit contenir au moins un chiffre','auth.name_length' => 'Le nom doit contenir au moins 2 caracteres','auth.name_letters' => 'Le nom ne peut contenir que des lettres et des espaces','auth.invalid_role' => 'Role invalide','auth.email_exists' => 'Cette adresse e-mail est deja utilisee','auth.phone_exists' => 'Ce numero de telephone est deja utilise','auth.registration_success' => 'Inscription reussie','auth.registration_failed' => 'Echec de l\'inscription',
    ],
    'rw' => [
        'common.language' => 'Ururimi','common.menu' => 'Ibikubiyemo','common.home' => 'Ahabanza','common.dashboard' => 'Imbonerahamwe','common.profile' => 'Umwirondoro','common.workers' => 'Abakozi','common.jobs' => 'Akazi','common.post_job' => 'Tangaza akazi','common.find_workers' => 'Shaka abakozi','common.my_jobs' => 'Akazi kanjye','common.bookings' => 'Bokingi','common.messages' => 'Ubutumwa','common.reviews' => 'Ibitekerezo','common.help' => 'Ubufasha','common.login' => 'Injira','common.register' => 'Iyandikishe','common.loading' => 'Birimo gutangazwa...','common.notifications' => 'Amatangazo','common.back_home' => 'Subira Ahabanza','common.next_step' => 'Intambwe ikurikira','common.previous' => 'Subira inyuma','common.phone_number' => 'Nimero ya telefoni','common.password' => 'Ijambobanga','common.email_address' => 'Imeli','common.first_name' => 'Izina rya mbere','common.last_name' => 'Izina rya nyuma','common.sign_in' => 'Injira','common.sign_up' => 'Iyandikishe','common.create_account' => 'Fungura konti','common.remember_me' => 'Unyibuke','common.forgot_password' => 'Wibagiwe ijambobanga?','common.terms' => 'Amabwiriza ya serivisi','common.privacy' => 'Politiki y\'ubwirinzi bwite','nav.profile_settings' => 'Igenamiterere rya profili','nav.my_reviews' => 'Ibitekerezo byanjye','nav.earnings' => 'Amafaranga nakuye mu kazi','nav.help_support' => 'Ubufasha na serivisi','nav.logout' => 'Sohoka','nav.confirm_logout' => 'Emeza ko usohoka','nav.confirm_logout_question' => 'Uremeza ko ushaka gusohoka?','nav.confirm_logout_text' => 'Uzoherezwa ku rubuga rw\'ibanze kandi uzakenera kongera kwinjira kugira ngo ukoreshe konti yawe.','nav.cancel' => 'Hagarika','nav.logout_now' => 'Sohoka ubu','index.nav_services' => 'Serivisi','index.nav_workers' => 'Abakozi','index.nav_how' => 'Uko bikorwa','index.hero_title' => 'Hura n\'abakozi bo mu rugo bizewe i Kigali','index.hero_subtitle' => 'Shaka abakozi bizewe bo gukora isuku, guteka, kurera abana n\'ibindi. Bose bemejwe kandi bafite amanota.','index.hero_find_workers' => 'Shaka abakozi','index.hero_post_job' => 'Tangaza akazi','index.hero_get_started' => 'Tangira','index.hero_browse_workers' => 'Reba abakozi','index.services_title' => 'Serivisi zacu','index.services_subtitle' => 'Serivisi z\'umwuga zo mu rugo zijyanye n\'ibyo ukeneye','index.featured_title' => 'Abakozi batoranyijwe','index.featured_subtitle' => 'Menya bamwe mu bakozi bo mu rugo bemejwe cyane i Kigali','index.view_all_workers' => 'Reba abakozi bose','index.no_workers_title' => 'Nta bakozi baraboneka kugeza ubu','index.no_workers_text' => 'Ba uwa mbere wiyandikisha nk\'umukozi utangire kubona akazi!','index.register_worker' => 'Iyandikishe nk\'umukozi','index.how_title' => 'Uko bikorwa','index.how_subtitle' => 'Hura n\'abakozi bo mu rugo mu ntambwe 3 zoroshye','index.cta_title' => 'Witeguye kubona umukozi wo mu rugo ukwiriye?','index.cta_text' => 'Jya hamwe n\'imiryango myinshi yo i Kigali yizeye Household Connect mu gushaka ubufasha bwo mu rugo','index.cta_browse_workers' => 'Reba abakozi','index.cta_post_job' => 'Tangaza akazi','index.cta_get_started' => 'Tangira nonaha','index.footer_explore' => 'Shakisha','index.footer_services' => 'Serivisi','index.footer_support' => 'Ubufasha','index.footer_contact' => 'Twandikire','index.footer_call' => 'Duhamagare','index.footer_email' => 'Imeli','index.footer_location' => 'Aho duherereye','index.footer_hours' => 'Amasaha','login.heading' => 'Injira','login.subtitle' => 'Injiza ibisabwa kugira ngo winjire muri konti yawe','login.submit' => 'Injira muri konti yawe','login.no_account' => 'Nta konti ufite?','login.logging_in' => 'Birimo kwinjira...','login.fill_all' => 'Nyamuneka uzuza imyanya yose','login.success' => 'Murakaza neza! Mwinjiye neza. Turakujyana ku rubuga rwawe ubu.','login.failed' => 'Kwinjira byanze. Ongera ugerageze.','login.network' => 'Ikibazo cya network. Reba internet wongere ugerageze.','login.forgot_soon' => 'Serivisi yo kongera ijambobanga iraje vuba!','register.heading' => 'Fungura konti','register.subtitle' => 'Jya hamwe n\'imiryango n\'abakozi benshi i Kigali','register.step_personal' => 'Amakuru yawe','register.step_account' => 'Konti','register.step_role' => 'Icyiciro','register.personal_heading' => 'Amakuru yihariye','register.personal_subtitle' => 'Tubwire ibikwerekeye','register.account_heading' => 'Fungura konti yawe','register.account_subtitle' => 'Tegura ibisabwa mu kwinjira','register.role_heading' => 'Hitamo icyiciro cyawe','register.role_subtitle' => 'Uzakooresha urubuga ute?','register.password_length' => 'Nibura inyuguti 8','register.password_upper' => 'Inyuguti nkuru imwe','register.password_lower' => 'Inyuguti nto imwe','register.password_number' => 'Umubare umwe','register.confirm_password' => 'Emeza ijambobanga','register.employer' => 'Umukoresha','register.employer_text' => 'Ndi gushaka abakozi bo mu rugo','register.worker' => 'Umukozi','register.worker_text' => 'Ndi gushaka amahirwe y\'akazi','register.already_account' => 'Usanzwe ufite konti?','register.creating' => 'Birimo gufungura konti...','register.create_submit' => 'Fungura konti','register.fill_required' => 'Nyamuneka uzuza ibisabwa byose','register.success' => 'Konti yafunguwe neza! Turakujyana ku rupapuro rwo kwinjira...','register.failed' => 'Kwiyandikisha byanze. Ongera ugerageze.','register.network' => 'Ikibazo cya network. Reba internet wongere ugerageze.','register.invalid_first' => 'Shyiramo izina ryawe rya mbere','register.invalid_last' => 'Shyiramo izina ryawe rya nyuma','register.invalid_email' => 'Shyiramo imeli yemewe','register.invalid_phone' => 'Shyiramo nimero ya telefoni','register.invalid_password' => 'Ijambobanga ntiryujuje ibisabwa','register.invalid_confirm' => 'Amagambo banga ntabwo ahura','register.invalid_role' => 'Hitamo icyiciro cyawe','register.invalid_terms' => 'Ugomba kwemera amabwiriza','auth.method_not_allowed' => 'Ubu buryo ntibwemerewe','auth.validation_failed' => 'Kwemeza byanze','auth.invalid_phone' => 'Imiterere ya nimero ya telefoni ntiyemewe','auth.invalid_credentials' => 'Nimero ya telefoni cyangwa ijambobanga sibyo','auth.login_success' => 'Kwinjira byagenze neza','auth.server_error' => 'Ikosa rya seriveri','auth.invalid_email' => 'Shyiramo imeli yemewe','auth.phone_required' => 'Shyiramo nimero ya telefoni yemewe','auth.password_length' => 'Ijambobanga rigomba kuba nibura inyuguti 8','auth.password_upper' => 'Ijambobanga rigomba kugira inyuguti nkuru nibura imwe','auth.password_lower' => 'Ijambobanga rigomba kugira inyuguti nto nibura imwe','auth.password_number' => 'Ijambobanga rigomba kugira umubare nibura umwe','auth.name_length' => 'Izina rigomba kuba nibura inyuguti 2','auth.name_letters' => 'Izina rigomba kuba rigizwe n\'inyuguti n\'imwanya gusa','auth.invalid_role' => 'Icyiciro nticyemewe','auth.email_exists' => 'Iyi imeli isanzwe ikoreshwa','auth.phone_exists' => 'Iyi nimero ya telefoni isanzwe ikoreshwa','auth.registration_success' => 'Kwiyandikisha byagenze neza','auth.registration_failed' => 'Kwiyandikisha byanze',
    ],
];

$APP_TRANSLATIONS['en'] = array_merge($APP_TRANSLATIONS['en'], [
    'index.stats_workers' => 'Trusted Workers',
    'index.stats_families' => 'Happy Families',
    'index.stats_jobs' => 'Jobs Completed',
    'index.stats_satisfaction' => 'Satisfaction Rate',
    'index.service_cleaning_title' => 'Professional Cleaning Services',
    'index.service_cleaning_text' => 'Experienced cleaners for thorough home and office cleaning services',
    'index.service_cooking_title' => 'Home Cooking Support',
    'index.service_cooking_text' => 'Skilled cooks for daily meals, family menus, and special food preparation',
    'index.service_childcare_title' => 'Childcare Assistance',
    'index.service_childcare_text' => 'Trusted caregivers to support children with safety, play, and daily routines',
    'index.service_elder_title' => 'Elder Care Support',
    'index.service_elder_text' => 'Compassionate helpers for companionship, assistance, and respectful daily care',
    'index.service_garden_title' => 'Gardening Help',
    'index.service_garden_text' => 'Reliable workers for garden maintenance, yard care, and outdoor cleaning',
    'index.service_driver_title' => 'Driver Services',
    'index.service_driver_text' => 'Experienced drivers for school runs, errands, appointments, and family transport',
]);

$APP_TRANSLATIONS['fr'] = array_merge($APP_TRANSLATIONS['fr'], [
    'index.stats_workers' => 'Travailleurs de confiance',
    'index.stats_families' => 'Familles satisfaites',
    'index.stats_jobs' => 'Missions realisees',
    'index.stats_satisfaction' => 'Taux de satisfaction',
    'index.service_cleaning_title' => 'Services de nettoyage professionnels',
    'index.service_cleaning_text' => 'Des agents de nettoyage experimentes pour un entretien complet de la maison et du bureau',
    'index.service_cooking_title' => 'Aide en cuisine a domicile',
    'index.service_cooking_text' => 'Des cuisiniers qualifies pour les repas quotidiens, les menus familiaux et les preparations speciales',
    'index.service_childcare_title' => 'Assistance pour la garde d\'enfants',
    'index.service_childcare_text' => 'Des accompagnateurs de confiance pour la securite, les jeux et la routine quotidienne des enfants',
    'index.service_elder_title' => 'Aide aux personnes agees',
    'index.service_elder_text' => 'Une assistance attentionnee pour la compagnie, le soutien et les soins du quotidien',
    'index.service_garden_title' => 'Aide au jardinage',
    'index.service_garden_text' => 'Des travailleurs fiables pour l\'entretien du jardin, de la cour et des espaces exterieurs',
    'index.service_driver_title' => 'Services de chauffeur',
    'index.service_driver_text' => 'Des conducteurs experimentes pour l\'ecole, les courses, les rendez-vous et les deplacements familiaux',
]);

$APP_TRANSLATIONS['rw'] = array_merge($APP_TRANSLATIONS['rw'], [
    'index.stats_workers' => 'Abakozi bizewe',
    'index.stats_families' => 'Imiryango yishimye',
    'index.stats_jobs' => 'Akazi karangiye',
    'index.stats_satisfaction' => 'Igipimo cyo kunyurwa',
    'index.service_cleaning_title' => 'Serivisi z\'isuku z\'umwuga',
    'index.service_cleaning_text' => 'Abakozi b\'isuku bafite uburambe mu gukora isuku inoze yo mu rugo no mu biro',
    'index.service_cooking_title' => 'Ubufasha bwo guteka mu rugo',
    'index.service_cooking_text' => 'Abatetsi b\'inararibonye ku mafunguro ya buri munsi, menu z\'umuryango n\'itegurwa ryihariye',
    'index.service_childcare_title' => 'Ubufasha bwo kurera abana',
    'index.service_childcare_text' => 'Abita ku bana bizewe bafasha mu mutekano, gukina no mu bikorwa bya buri munsi',
    'index.service_elder_title' => 'Ubufasha ku bageze mu zabukuru',
    'index.service_elder_text' => 'Abafasha bafite umutima mwiza mu guherekeza, gufasha no kwita ku bageze mu zabukuru',
    'index.service_garden_title' => 'Ubufasha bwo kwita ku busitani',
    'index.service_garden_text' => 'Abakozi bizewe mu kwita ku busitani, mu gikari no mu isuku yo hanze',
    'index.service_driver_title' => 'Serivisi zo gutwara',
    'index.service_driver_text' => 'Abashoferi b\'inararibonye ku kujyana abana ku ishuri, gukora ingendo, gahunda n\'ingendo z\'umuryango',
]);

$APP_TRANSLATIONS['en'] = array_merge($APP_TRANSLATIONS['en'], [
    'forgot.heading' => 'Forgot Password',
    'forgot.subtitle' => 'Enter your email address or phone number and we will send you a reset link.',
    'forgot.identifier' => 'Email Address or Phone Number',
    'forgot.identifier_placeholder' => 'e.g., name@example.com or 0781234567',
    'forgot.submit' => 'Send Reset Link',
    'forgot.submitting' => 'Sending reset link...',
    'forgot.success' => 'If an account matches your details, a password reset link has been sent.',
    'forgot.back_login' => 'Back to Login',
    'forgot.invalid_identifier' => 'Please enter your email address or phone number.',
    'forgot.email_failed' => 'We could not send the reset email right now. Please try again later.',
    'reset.heading' => 'Reset Password',
    'reset.subtitle' => 'Create a new password for your account.',
    'reset.password' => 'New Password',
    'reset.confirm_password' => 'Confirm New Password',
    'reset.submit' => 'Update Password',
    'reset.submitting' => 'Updating password...',
    'reset.success' => 'Your password has been updated successfully. You can now log in.',
    'reset.invalid_token' => 'This reset link is invalid or has expired.',
    'reset.password_mismatch' => 'Passwords do not match.',
    'reset.password_rules' => 'Use at least 8 characters, including uppercase, lowercase, and a number.',
    'reset.go_login' => 'Go to Login',
    'reset.token_required' => 'Reset token is required.',
    'auth.reset_request_failed' => 'Unable to process your reset request.',
    'auth.reset_email_failed' => 'Unable to send reset email right now.',
    'auth.reset_invalid_token' => 'Reset link is invalid or has expired.',
    'auth.reset_success' => 'Password reset successful.',
]);

$APP_TRANSLATIONS['fr'] = array_merge($APP_TRANSLATIONS['fr'], [
    'forgot.heading' => 'Mot de passe oublie',
    'forgot.subtitle' => 'Entrez votre adresse e-mail ou votre numero de telephone et nous vous enverrons un lien de reinitialisation.',
    'forgot.identifier' => 'Adresse e-mail ou numero de telephone',
    'forgot.identifier_placeholder' => 'ex. nom@exemple.com ou 0781234567',
    'forgot.submit' => 'Envoyer le lien',
    'forgot.submitting' => 'Envoi du lien...',
    'forgot.success' => 'Si un compte correspond a vos informations, un lien de reinitialisation a ete envoye.',
    'forgot.back_login' => 'Retour a la connexion',
    'forgot.invalid_identifier' => 'Veuillez saisir votre adresse e-mail ou votre numero de telephone.',
    'forgot.email_failed' => 'Nous ne pouvons pas envoyer l\'e-mail de reinitialisation pour le moment. Veuillez reessayer plus tard.',
    'reset.heading' => 'Reinitialiser le mot de passe',
    'reset.subtitle' => 'Creez un nouveau mot de passe pour votre compte.',
    'reset.password' => 'Nouveau mot de passe',
    'reset.confirm_password' => 'Confirmer le nouveau mot de passe',
    'reset.submit' => 'Mettre a jour le mot de passe',
    'reset.submitting' => 'Mise a jour du mot de passe...',
    'reset.success' => 'Votre mot de passe a ete mis a jour avec succes. Vous pouvez maintenant vous connecter.',
    'reset.invalid_token' => 'Ce lien de reinitialisation est invalide ou a expire.',
    'reset.password_mismatch' => 'Les mots de passe ne correspondent pas.',
    'reset.password_rules' => 'Utilisez au moins 8 caracteres, avec une majuscule, une minuscule et un chiffre.',
    'reset.go_login' => 'Aller a la connexion',
    'reset.token_required' => 'Le jeton de reinitialisation est requis.',
    'auth.reset_request_failed' => 'Impossible de traiter votre demande de reinitialisation.',
    'auth.reset_email_failed' => 'Impossible d\'envoyer l\'e-mail de reinitialisation pour le moment.',
    'auth.reset_invalid_token' => 'Le lien de reinitialisation est invalide ou a expire.',
    'auth.reset_success' => 'Reinitialisation du mot de passe reussie.',
]);

$APP_TRANSLATIONS['rw'] = array_merge($APP_TRANSLATIONS['rw'], [
    'forgot.heading' => 'Wibagiwe ijambobanga',
    'forgot.subtitle' => 'Andika imeli yawe cyangwa nimero ya telefoni maze twohereze link yo kongera gushyiraho ijambobanga.',
    'forgot.identifier' => 'Imeli cyangwa nimero ya telefoni',
    'forgot.identifier_placeholder' => 'nko: izina@example.com cyangwa 0781234567',
    'forgot.submit' => 'Ohereza link',
    'forgot.submitting' => 'Turimo kohereza link...',
    'forgot.success' => 'Niba konti ihuye n\'amakuru watanze, twohereje link yo kongera gushyiraho ijambobanga.',
    'forgot.back_login' => 'Subira ku kwinjira',
    'forgot.invalid_identifier' => 'Andika imeli yawe cyangwa nimero ya telefoni.',
    'forgot.email_failed' => 'Ntidushoboye kohereza imeli yo kongera ijambobanga ubu. Ongera ugerageze nyuma.',
    'reset.heading' => 'Shyiraho ijambobanga rishya',
    'reset.subtitle' => 'Shyiraho ijambobanga rishya kuri konti yawe.',
    'reset.password' => 'Ijambobanga rishya',
    'reset.confirm_password' => 'Emeza ijambobanga rishya',
    'reset.submit' => 'Hindura ijambobanga',
    'reset.submitting' => 'Turimo guhindura ijambobanga...',
    'reset.success' => 'Ijambobanga ryawe ryahinduwe neza. Ubu ushobora kwinjira.',
    'reset.invalid_token' => 'Iyi link yo kongera ijambobanga ntiyemewe cyangwa yararengeje igihe.',
    'reset.password_mismatch' => 'Amagambo banga ntabwo ahura.',
    'reset.password_rules' => 'Koresha nibura inyuguti 8 zirimo inyuguti nkuru, nto n\'umubare.',
    'reset.go_login' => 'Jya ku kwinjira',
    'reset.token_required' => 'Token yo kongera ijambobanga irakenewe.',
    'auth.reset_request_failed' => 'Ntibishobotse gutunganya ubusabe bwo kongera ijambobanga.',
    'auth.reset_email_failed' => 'Ntidushoboye kohereza imeli yo kongera ijambobanga ubu.',
    'auth.reset_invalid_token' => 'Link yo kongera ijambobanga ntiyemewe cyangwa yararengeje igihe.',
    'auth.reset_success' => 'Kongera ijambobanga byagenze neza.',
]);

function initialize_language()
{
    global $AVAILABLE_LANGUAGES;
    if (isset($_GET['lang']) && array_key_exists($_GET['lang'], $AVAILABLE_LANGUAGES)) {
        $_SESSION['lang'] = $_GET['lang'];
    }
    if (empty($_SESSION['lang']) || !array_key_exists($_SESSION['lang'], $AVAILABLE_LANGUAGES)) {
        $_SESSION['lang'] = 'en';
    }
}

function current_language()
{
    return $_SESSION['lang'] ?? 'en';
}

function supported_languages()
{
    global $AVAILABLE_LANGUAGES;
    return $AVAILABLE_LANGUAGES;
}

function t($key)
{
    global $APP_TRANSLATIONS;
    $lang = current_language();
    return $APP_TRANSLATIONS[$lang][$key] ?? $APP_TRANSLATIONS['en'][$key] ?? $key;
}

function language_switch_url($lang)
{
    $request_uri = $_SERVER['REQUEST_URI'] ?? ($_SERVER['PHP_SELF'] ?? '');
    $path = parse_url($request_uri, PHP_URL_PATH) ?: '';
    parse_str((string) parse_url($request_uri, PHP_URL_QUERY), $query);
    $query['lang'] = $lang;
    return ($path ?: '') . '?' . http_build_query($query);
}

function runtime_translation_dictionary()
{
    return [
        'fr' => [
            'Household Connect' => 'Household Connect',
            'Dashboard' => 'Tableau de bord',
            'Login' => 'Connexion',
            'Register' => 'Inscription',
            'Profile' => 'Profil',
            'Profile Settings' => 'Parametres du profil',
            'Workers' => 'Travailleurs',
            'Jobs' => 'Offres',
            'Messages' => 'Messages',
            'Help' => 'Aide',
            'Help & Support' => 'Aide et support',
            'Logout' => 'Deconnexion',
            'Post Job' => 'Publier une offre',
            'Job Applications' => 'Candidatures',
            'Find Workers' => 'Trouver des travailleurs',
            'Find Jobs' => 'Trouver des offres',
            'My Jobs' => 'Mes offres',
            'My Applications' => 'Mes candidatures',
            'Bookings' => 'Reservations',
            'Active Jobs' => 'Offres actives',
            'Earnings' => 'Revenus',
            'Notifications' => 'Notifications',
            'Loading...' => 'Chargement...',
            'Close' => 'Fermer',
            'Cancel' => 'Annuler',
            'Save' => 'Enregistrer',
            'Save Changes' => 'Enregistrer les modifications',
            'Delete' => 'Supprimer',
            'Edit' => 'Modifier',
            'Update' => 'Mettre a jour',
            'Update Profile' => 'Mettre a jour le profil',
            'Browse Jobs' => 'Parcourir les offres',
            'Browse Workers' => 'Voir les travailleurs',
            'Available Jobs' => 'Offres disponibles',
            'Available Workers' => 'Travailleurs disponibles',
            'Recent Job Postings' => 'Offres recentes',
            'Quick Actions' => 'Actions rapides',
            'Create Profile Now' => 'Creer le profil maintenant',
            'Create Booking' => 'Creer une reservation',
            'Book Worker' => 'Reserver le travailleur',
            'Book Now' => 'Reserver',
            'Contact Worker' => 'Contacter le travailleur',
            'Contact' => 'Contacter',
            'Send Message' => 'Envoyer le message',
            'Subject' => 'Sujet',
            'Message' => 'Message',
            'Start Date' => 'Date de debut',
            'End Date' => 'Date de fin',
            'Service Type' => 'Type de service',
            'Additional Notes' => 'Notes supplementaires',
            'Search workers...' => 'Rechercher des travailleurs...',
            'Search jobs...' => 'Rechercher des offres...',
            'Search...' => 'Rechercher...',
            'All Types' => 'Tous les types',
            'Cleaning' => 'Nettoyage',
            'Cooking' => 'Cuisine',
            'Childcare' => 'Garde d\'enfants',
            'Gardening' => 'Jardinage',
            'Elder Care' => 'Aide aux personnes agees',
            'Eldercare' => 'Aide aux personnes agees',
            'Other' => 'Autre',
            'Welcome back' => 'Bon retour',
            'No available jobs at the moment' => 'Aucune offre disponible pour le moment',
            'No recent job postings' => 'Aucune offre recente',
            'No workers found matching your criteria.' => 'Aucun travailleur ne correspond a vos criteres.',
            'No Workers Available Yet' => 'Aucun travailleur disponible pour le moment',
            'Register as Worker' => 'S\'inscrire comme travailleur',
            'Terms of Service' => 'Conditions d\'utilisation',
            'Privacy Policy' => 'Politique de confidentialite',
            'Phone Number' => 'Numero de telephone',
            'Password' => 'Mot de passe',
            'Email Address' => 'Adresse e-mail',
            'First Name' => 'Prenom',
            'Last Name' => 'Nom',
            'Remember me' => 'Se souvenir de moi',
            'Forgot Password?' => 'Mot de passe oublie ?',
            'Sign up' => 'S\'inscrire',
            'Sign in' => 'Se connecter',
            'Back to Home' => 'Retour a l\'accueil',
            'Create Account' => 'Creer un compte',
            'Next Step' => 'Etape suivante',
            'Previous' => 'Precedent',
            'Role' => 'Role',
            'Employer' => 'Employeur',
            'Worker' => 'Travailleur',
            'Language' => 'Langue',
            'Menu' => 'Menu',
            'Home' => 'Accueil',
            'Reviews' => 'Avis',
            'Settings' => 'Parametres',
            'Reports' => 'Rapports',
            'Transactions' => 'Transactions',
            'Users' => 'Utilisateurs',
            'Admin' => 'Admin',
        ],
        'rw' => [
            'Household Connect' => 'Household Connect',
            'Dashboard' => 'Imbonerahamwe',
            'Login' => 'Injira',
            'Register' => 'Iyandikishe',
            'Profile' => 'Umwirondoro',
            'Profile Settings' => 'Igenamiterere rya profili',
            'Workers' => 'Abakozi',
            'Jobs' => 'Akazi',
            'Messages' => 'Ubutumwa',
            'Help' => 'Ubufasha',
            'Help & Support' => 'Ubufasha na serivisi',
            'Logout' => 'Sohoka',
            'Post Job' => 'Tangaza akazi',
            'Job Applications' => 'Abasabye akazi',
            'Find Workers' => 'Shaka abakozi',
            'Find Jobs' => 'Shaka akazi',
            'My Jobs' => 'Akazi kanjye',
            'My Applications' => 'Ubusabe bwanjye',
            'Bookings' => 'Bokingi',
            'Active Jobs' => 'Akazi gakora',
            'Earnings' => 'Amafaranga nakuye mu kazi',
            'Notifications' => 'Amatangazo',
            'Loading...' => 'Birimo gutangazwa...',
            'Close' => 'Funga',
            'Cancel' => 'Hagarika',
            'Save' => 'Bika',
            'Save Changes' => 'Bika impinduka',
            'Delete' => 'Siba',
            'Edit' => 'Hindura',
            'Update' => 'Vugurura',
            'Update Profile' => 'Hindura profili',
            'Browse Jobs' => 'Reba akazi',
            'Browse Workers' => 'Reba abakozi',
            'Available Jobs' => 'Akazi kaboneka',
            'Available Workers' => 'Abakozi baboneka',
            'Recent Job Postings' => 'Akazi katangajwe vuba',
            'Quick Actions' => 'Ibikorwa byihuse',
            'Create Profile Now' => 'Kora profili nonaha',
            'Create Booking' => 'Kora bokingi',
            'Book Worker' => 'Buka umukozi',
            'Book Now' => 'Buka nonaha',
            'Contact Worker' => 'Vugana n\'umukozi',
            'Contact' => 'Vugana',
            'Send Message' => 'Ohereza ubutumwa',
            'Subject' => 'Umutwe',
            'Message' => 'Ubutumwa',
            'Start Date' => 'Itariki yo gutangira',
            'End Date' => 'Itariki yo kurangiza',
            'Service Type' => 'Ubwoko bwa serivisi',
            'Additional Notes' => 'Andi makuru',
            'Search workers...' => 'Shaka abakozi...',
            'Search jobs...' => 'Shaka akazi...',
            'Search...' => 'Shaka...',
            'All Types' => 'Ubwoko bwose',
            'Cleaning' => 'Isuku',
            'Cooking' => 'Guteka',
            'Childcare' => 'Kurera abana',
            'Gardening' => 'Ubusitani',
            'Elder Care' => 'Kwita ku bageze mu zabukuru',
            'Eldercare' => 'Kwita ku bageze mu zabukuru',
            'Other' => 'Ibindi',
            'Welcome back' => 'Murakaza neza',
            'No available jobs at the moment' => 'Nta kazi kaboneka ubu',
            'No recent job postings' => 'Nta kazi katangajwe vuba',
            'No workers found matching your criteria.' => 'Nta bakozi bahuye n\'ibyo washakaga.',
            'No Workers Available Yet' => 'Nta bakozi baraboneka kugeza ubu',
            'Register as Worker' => 'Iyandikishe nk\'umukozi',
            'Terms of Service' => 'Amabwiriza ya serivisi',
            'Privacy Policy' => 'Politiki y\'ubwirinzi bwite',
            'Phone Number' => 'Nimero ya telefoni',
            'Password' => 'Ijambobanga',
            'Email Address' => 'Imeli',
            'First Name' => 'Izina rya mbere',
            'Last Name' => 'Izina rya nyuma',
            'Remember me' => 'Unyibuke',
            'Forgot Password?' => 'Wibagiwe ijambobanga?',
            'Sign up' => 'Iyandikishe',
            'Sign in' => 'Injira',
            'Back to Home' => 'Subira Ahabanza',
            'Create Account' => 'Fungura konti',
            'Next Step' => 'Intambwe ikurikira',
            'Previous' => 'Subira inyuma',
            'Role' => 'Icyiciro',
            'Employer' => 'Umukoresha',
            'Worker' => 'Umukozi',
            'Language' => 'Ururimi',
            'Menu' => 'Ibikubiyemo',
            'Home' => 'Ahabanza',
            'Reviews' => 'Ibitekerezo',
            'Settings' => 'Igenamiterere',
            'Reports' => 'Raporo',
            'Transactions' => 'Ibikorwa by\'amafaranga',
            'Users' => 'Abakoresha',
            'Admin' => 'Admin',
        ],
    ];
}

function language_switch_urls()
{
    $urls = [];
    foreach (supported_languages() as $code => $language) {
        $urls[$code] = language_switch_url($code);
    }
    return $urls;
}
